### ISSUE TITLE
TypeError: argument of type 'method' is not iterable

### ISSUE THREAD

**Issue by jhyuklee** [uwnlp/piqa#5]
Training using
```
$ python main.py baseline --cuda
```
and testing with
```
$ python main.py baseline --cuda --mode test --iteration 501
```

makes an error as follows:
```
...
Model loaded from /tmp/piqa/squad/save/501/model.pt
Traceback (most recent call last):
  File "main.py", line 257, in <module>
    main()
  File "main.py", line 236, in main
    test(args)
  File "main.py", line 162, in test
    test_dataset = tuple(processor.preprocess(example) for example in test_examples)
  File "main.py", line 162, in <genexpr>
    test_dataset = tuple(processor.preprocess(example) for example in test_examples)
  File "/home/jinhyuk/github/piqa/squad/baseline/processor.py", line 124, in preprocess
    context_word_idxs = tuple(map(self._word2idx, context_words))
  File "/home/jinhyuk/github/piqa/squad/baseline/processor.py", line 276, in _word2idx
    return self._word2idx_dict[word] if word in self._word2idx_dict else 1
TypeError: argument of type 'method' is not iterable
```

Code version: https://github.com/uwnlp/piqa/commit/fa113ab2e6cfcec4951d27f6cd4ada6b610c3238

**Comment by jhyuklee** [comment]
```
python main.py baseline --cuda --mode embed_context --iteration 501 --test_path $SQUAD_DEV_CONTEXT_PATH
python main.py baseline --cuda --mode embed_question --iteration 501 --test_path $SQUAD_DEV_QUESTION_PATH
```

commands for embedding context and question cause the same error.

**Comment by jhyuklee** [comment]
state_dict() function seems to be the problem.

https://github.com/uwnlp/piqa/blob/fa113ab2e6cfcec4951d27f6cd4ada6b610c3238/squad/baseline/processor.py#L106-L115

I think it should save self._word2idx_dict instead of self._word2idx.

**Comment by jhyuklee** [comment]
https://github.com/uwnlp/piqa/commit/5ba4f1c4a223ebbf60f54b80b6803b423b8e8dcf solves the problem. 
Please check if it's right. @seominjoon

**Comment by seominjoon** [comment]
Thanks! Will need to put some unit tests in the future...
